### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by gelsas** [phuonglm/yi-hack-webui#1]
Hello!

I have a QNAP NAS and want to use your software but I haven't used docker before so I have no idea how to do it manually. Could you create an docker image and put it on: https://hub.docker.com/ ? Then I could install it with one click in the "Container Station" (Thats how QNAP calls the docker management software they have)

regards

**Comment by gelsas** [comment]
I tried to install it via the yaml file but i needed to change the path so it works:
Now the yihackwebui_cronjob_1 docker seems not to work i get this error:
bash: /app/yiantcopy.sh: Permission denied  

This is my yaml file:
```
version: '2'
services:
  webui:
    build:
      context: /share/CACHEDEV1_DATA/Multimedia/Yi-Home/webui/
      dockerfile: Dockerfile
    ports:
      - "1234:80"
    restart: always
    cpuset: "0"
    volumes:
      - ./data:/share/CACHEDEV1_DATA/Multimedia/Yi-Home/app/data
    env_file:
      /share/CACHEDEV1_DATA/Multimedia/Yi-Home/.env
  cronjob:
    build:
      context: /share/CACHEDEV1_DATA/Multimedia/Yi-Home/cronjob/
      dockerfile: Dockerfile
    volumes:
      - ./data:/share/CACHEDEV1_DATA/Multimedia/Yi-Home/data
    restart: always
    mem_limit: 100M
    env_file:
      /share/CACHEDEV1_DATA/Multimedia/Yi-Home/.env
```
How can I make it work?
